Docs: update reproducible builds guide
readthedocs/readthedocs.org pull request #10939
Opened 2023-12-01 14:03 UTC by duboism

As discussed in #10924, we propose to update the reproducible builds guide (`docs/user/guides/`reproducible-builds.rst`). The goals are:

  - update instruction for config v2 file
  - clarify that versions in the guide are just example and not recommended
  - don't use the buggy `sphinx=5.3.0` in the example

2023-12-05 21:52 UTC, duboism commented
I finished the main proposed modifications.

However, I don't understand the "✅ Good:" badge in **Pin your transitive dependencies**. Any thoughts ?

2023-12-11 12:46 UTC, humitos requested changes
Thanks for the PR! I think it's good and ready to merge after some small changes 👍🏼

2024-01-10 17:54 UTC, duboism commented on docs/user/guides/reproducible-builds.rst
> +   readthedocs-sphinx-search==0.3.1
OK, I reverted the commits to restore the old versions.

2024-01-10 18:31 UTC, duboism commented on docs/user/guides/reproducible-builds.rst
> +   It is up to you to find those versions.
Thanks :)

2024-01-10 18:46 UTC, duboism commented on docs/user/guides/reproducible-builds.rst
> +See the ``build.tools`` key in the documentation.
OK. Given the previous remark (link to https://docs.readthedocs.io/en/stable/config-file/), we can transform the previous paragraph (Before reading this page) to an admonition just to mention that fixing the versions of the main tools in this file is a first step toward reproducibility.

2024-01-10 18:57 UTC, duboism commented
Sorry for the delay. I commented on the various points you raised.

2024-01-21 22:28 UTC, duboism commented
Any news ?

2024-09-05 14:29 UTC, duboism commented
Still no news ?

2024-09-05 20:54 UTC, ericholscher commented
This PR has conflicts -- I think because we addressed the change with the YAML file being required already. So it's probably fine to update this to just include the warning, and I'm fine to merge it.

2024-09-26 14:42 UTC, htech9 commented
@duboism You may want to fix the conflicts and address the comment above.

2024-09-26 17:23 UTC, duboism commented
@htech9, sorry I was busy on other duties. I will adress that quickly.

2024-09-29 16:29 UTC, duboism commented
As requested, I updated the branch to just include the warning (and an obvious typo).

2024-09-30 21:37 UTC, ericholscher approved these changes
Thanks :)

2024-09-30 21:37 UTC, merged

2024-09-30 21:42 UTC, duboism commented
Thanks for merging. The world is a little better now :)