Creating Task to Restore an Old State of Database
readthedocs/readthedocs.org pull request #8708
Opened 2021-11-24 01:01 UTC by vitorsv1

Fix Issue #7761

2021-11-24 08:53 UTC, humitos requested changes
Hi! Thanks for opening the PR 😄 

It seems that you only added a paragraph in the documentation but I'm not seeing the code for that task, `restoredb`. Will you open another PR in the `common` repository?

2021-11-24 10:42 UTC, vitorsv1 commented
> Hi! Thanks for opening the PR 😄
> 
> It seems that you only added a paragraph in the documentation but I'm not seeing the code for that task, `restoredb`. Will you open another PR in the `common` repository?

Hi @humitos !

I just made the PR in the common repository, it seems I forgot to do it before 😆

2022-03-02 11:43 UTC, humitos commented
This is blocked on https://github.com/readthedocs/common/pull/98

2026-08-21 04:19 UTC, ericholscher commented
Going to close this since it's quite outdated at this point.

2026-08-21 04:19 UTC, closed without merging