Log conda version and docker image hash when creating a container.
readthedocs/readthedocs.org pull request #8755
Opened 2021-12-11 18:52 UTC by dogukanteber

2022-01-05 15:52 UTC, humitos requested changes
Thanks for your PR! I'm requesting changes because we need to run the command inside the Docker container. We can't use `subprocess.run` for this unfortunately.

2022-01-05 21:02 UTC, dogukanteber commented on readthedocs/doc_builder/environments.py
> +            )
Thank you for your comment @humitos. I am dealing with my finals now. Would that be okay if a take a look at it in the next week?

2022-01-10 10:52 UTC, humitos commented on readthedocs/doc_builder/environments.py
> +            )
Yes! 👍🏼

2022-01-16 12:02 UTC, dogukanteber commented on readthedocs/doc_builder/environments.py
> +            )
I have made some changes @humitos.

2022-01-20 10:54 UTC, astrojuanlu commented
Hi @dogukanteber ! Some tests are still failing: `E       AttributeError: 'NoneType' object has no attribute 'container_id'` (see the red Circle CI check. Have you already finished your finals? :)

2022-01-20 12:55 UTC, dogukanteber commented
Hello @astrojuanlu. Yes, I have finished my finals. I have not realized some tests failed. I did some changes but it did not work. Right now, I am stuck. I cannot find a way out. Do you have any recommendations on how should I proceed?

2022-05-02 18:04 UTC, ericholscher commented
Thanks for the PR. This can now be accomplished with `build.jobs` config option, so I'm going to close this.

https://docs.readthedocs.io/en/latest/config-file/v2.html#build-jobs

2022-05-02 18:04 UTC, closed without merging